apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s88px0m5s-go
  janus-idp.io/tekton: s88px0m5s-go
  backstage.io/kubernetes-id: s88px0m5s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s88px0m5s-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
