apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s88px0m5s-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s88px0m5s-go 
  name: s88px0m5s-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s88px0m5s-go 
