apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s88px0m5s-go 
  janus-idp.io/tekton: s88px0m5s-go
  backstage.io/kubernetes-id: s88px0m5s-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s88px0m5s-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml