apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s88px0m5s-go-gitops
  description: This is GitOps manifest for s88px0m5s-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=s88px0m5s-go
    backstage.io/kubernetes-id: s88px0m5s-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s88px0m5s-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s88px0m5s-go
